osx_image: xcode9.4
podfile: Podfile
language: objective-c
script:
- xcodebuild -workspace Endo-iOS.xcworkspace -scheme "Endo-iOSTests" -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.4' test
